import type { Icd10Entry } from './types.js';

const c = (code: string, name: string, chronic = false): Icd10Entry => (chronic ? { code, name, chronic } : { code, name });

/**
 * Tập con ICD-10 phổ biến ở phòng mạch nội và nhi, tên tiếng Việt theo cách gọi thông dụng.
 * MINH HỌA: thay bằng bộ ICD-10 tiếng Việt do Bộ Y tế ban hành (cần xác nhận nguồn và giấy phép) trước khi dùng thật.
 */
export const ICD10: readonly Icd10Entry[] = [
  // Hô hấp
  c('J00', 'Viêm mũi họng cấp (cảm thường)'),
  c('J01.9', 'Viêm xoang cấp, không đặc hiệu'),
  c('J02.9', 'Viêm họng cấp, không đặc hiệu'),
  c('J03.9', 'Viêm amidan cấp, không đặc hiệu'),
  c('J04.0', 'Viêm thanh quản cấp'),
  c('J05.0', 'Viêm thanh khí quản cấp (croup)'),
  c('J06.9', 'Nhiễm trùng đường hô hấp trên cấp, không đặc hiệu'),
  c('J10.1', 'Cúm có biểu hiện hô hấp, đã xác định virus cúm'),
  c('J11.1', 'Cúm có biểu hiện hô hấp, chưa xác định virus'),
  c('J15.9', 'Viêm phổi do vi khuẩn, không đặc hiệu'),
  c('J18.9', 'Viêm phổi, không đặc hiệu'),
  c('J20.9', 'Viêm phế quản cấp, không đặc hiệu'),
  c('J21.9', 'Viêm tiểu phế quản cấp, không đặc hiệu'),
  c('J30.4', 'Viêm mũi dị ứng, không đặc hiệu'),
  c('J31.0', 'Viêm mũi mạn'),
  c('J32.9', 'Viêm xoang mạn, không đặc hiệu'),
  c('J40', 'Viêm phế quản, không xác định cấp hay mạn'),
  c('J44.9', 'Bệnh phổi tắc nghẽn mạn tính, không đặc hiệu', true),
  c('J45.9', 'Hen, không đặc hiệu', true),
  c('R05', 'Ho'),
  c('R06.0', 'Khó thở'),
  // Nhiễm trùng, tiêu hóa
  c('A08.4', 'Nhiễm virus đường ruột, không đặc hiệu'),
  c('A09', 'Tiêu chảy và viêm dạ dày - ruột do nhiễm khuẩn'),
  c('A90', 'Sốt xuất huyết Dengue'),
  c('B01.9', 'Thủy đậu không biến chứng'),
  c('B02.9', 'Zona không biến chứng'),
  c('B05.9', 'Sởi không biến chứng'),
  c('B06.9', 'Rubella không biến chứng'),
  c('B08.4', 'Bệnh tay chân miệng (viêm miệng do enterovirus có phát ban)'),
  c('B26.9', 'Quai bị không biến chứng'),
  c('B34.9', 'Nhiễm virus, không đặc hiệu'),
  c('B35.3', 'Nấm bàn chân'),
  c('B35.4', 'Nấm da thân'),
  c('B36.0', 'Lang ben'),
  c('B37.0', 'Tưa miệng (nấm Candida miệng)'),
  c('B86', 'Ghẻ'),
  c('K21.9', 'Trào ngược dạ dày - thực quản không viêm thực quản'),
  c('K25.9', 'Loét dạ dày, không đặc hiệu'),
  c('K26.9', 'Loét tá tràng, không đặc hiệu'),
  c('K29.7', 'Viêm dạ dày, không đặc hiệu'),
  c('K30', 'Khó tiêu'),
  c('K52.9', 'Viêm dạ dày - ruột và đại tràng không nhiễm khuẩn, không đặc hiệu'),
  c('K58.9', 'Hội chứng ruột kích thích không tiêu chảy'),
  c('K59.0', 'Táo bón'),
  c('K76.0', 'Gan nhiễm mỡ', true),
  c('R10.4', 'Đau bụng khác và không đặc hiệu'),
  c('R11', 'Buồn nôn và nôn'),
  c('R19.7', 'Tiêu chảy, không đặc hiệu'),
  // Tim mạch, nội tiết, chuyển hóa
  c('I10', 'Tăng huyết áp vô căn (nguyên phát)', true),
  c('E03.9', 'Suy giáp, không đặc hiệu', true),
  c('E04.9', 'Bướu giáp không độc, không đặc hiệu', true),
  c('E05.9', 'Nhiễm độc giáp, không đặc hiệu', true),
  c('E10.9', 'Đái tháo đường typ 1, không biến chứng', true),
  c('E11.9', 'Đái tháo đường typ 2, không biến chứng', true),
  c('E46', 'Suy dinh dưỡng protein - năng lượng, không đặc hiệu'),
  c('E55.9', 'Thiếu vitamin D, không đặc hiệu'),
  c('E66.9', 'Béo phì, không đặc hiệu'),
  c('E78.5', 'Rối loạn lipid máu, không đặc hiệu', true),
  c('E86', 'Mất nước'),
  c('D50.9', 'Thiếu máu thiếu sắt, không đặc hiệu'),
  c('D64.9', 'Thiếu máu, không đặc hiệu'),
  c('M10.9', 'Gút, không đặc hiệu', true),
  // Tiết niệu, phụ khoa
  c('N20.0', 'Sỏi thận'),
  c('N30.0', 'Viêm bàng quang cấp'),
  c('N39.0', 'Nhiễm khuẩn đường tiết niệu, vị trí không xác định'),
  c('N76.0', 'Viêm âm đạo cấp'),
  // Cơ xương khớp
  c('M17.9', 'Thoái hóa khớp gối, không đặc hiệu', true),
  c('M19.9', 'Thoái hóa khớp, không đặc hiệu', true),
  c('M25.5', 'Đau khớp'),
  c('M47.9', 'Thoái hóa cột sống, không đặc hiệu', true),
  c('M54.2', 'Đau cột sống cổ'),
  c('M54.5', 'Đau vùng thắt lưng'),
  c('M79.1', 'Đau cơ'),
  // Thần kinh, triệu chứng chung
  c('F41.9', 'Rối loạn lo âu, không đặc hiệu'),
  c('G43.9', 'Đau nửa đầu (migraine), không đặc hiệu'),
  c('G47.0', 'Mất ngủ'),
  c('R00.2', 'Hồi hộp, đánh trống ngực'),
  c('R04.0', 'Chảy máu cam'),
  c('R07.4', 'Đau ngực, không đặc hiệu'),
  c('R21', 'Phát ban và ban da không đặc hiệu'),
  c('R42', 'Chóng mặt và rối loạn thăng bằng'),
  c('R50.9', 'Sốt, không đặc hiệu'),
  c('R51', 'Đau đầu'),
  c('R53', 'Mệt mỏi, khó chịu'),
  // Tai mũi họng, mắt, răng
  c('H00.0', 'Lẹo mắt và viêm sâu khác của mi mắt'),
  c('H10.9', 'Viêm kết mạc, không đặc hiệu'),
  c('H52.1', 'Cận thị'),
  c('H60.9', 'Viêm tai ngoài, không đặc hiệu'),
  c('H61.2', 'Ráy tai làm tắc ống tai'),
  c('H65.9', 'Viêm tai giữa không mủ, không đặc hiệu'),
  c('H66.9', 'Viêm tai giữa, không đặc hiệu'),
  c('K00.7', 'Hội chứng mọc răng'),
  c('K02.9', 'Sâu răng, không đặc hiệu'),
  // Da liễu
  c('L02.9', 'Áp xe da, nhọt, hậu bối, không đặc hiệu'),
  c('L08.9', 'Nhiễm khuẩn da tại chỗ, không đặc hiệu'),
  c('L20.9', 'Viêm da cơ địa, không đặc hiệu'),
  c('L23.9', 'Viêm da tiếp xúc dị ứng, không rõ nguyên nhân'),
  c('L30.9', 'Viêm da, không đặc hiệu'),
  c('L50.9', 'Mày đay, không đặc hiệu'),
  c('L70.0', 'Mụn trứng cá thông thường'),
  // Khám và cấp thuốc
  c('Z00.0', 'Khám sức khỏe tổng quát'),
  c('Z00.1', 'Khám sức khỏe định kỳ cho trẻ em'),
  c('Z76.0', 'Cấp lại đơn thuốc', true),
];
