import { drugCode } from '@phongmach/catalogs';
import type { TrialCase } from './types.js';

const D = drugCode;
const NACL_MUI = 'Nhỏ mỗi bên mũi 2–3 giọt, 3–4 lần/ngày';

const AMOXICILLIN = D('Amoxicillin 500 mg');
const AMOX_CLAV = D('Amoxicillin + acid clavulanic 625 mg');
const AZITHROMYCIN = D('Azithromycin 500 mg');
const PARACETAMOL = D('Paracetamol 500 mg');
const CETIRIZIN = D('Cetirizin 10 mg');
const NACL = D('Natri clorid 0,9% (nhỏ mũi)');
const OMEPRAZOL = D('Omeprazol 20 mg');
const DOMPERIDON = D('Domperidon 10 mg');
const ANTACID = D('Nhôm hydroxyd + magnesi hydroxyd');
const AMLODIPIN = D('Amlodipin 5 mg');
const ATORVASTATIN = D('Atorvastatin 20 mg');
const METFORMIN_500 = D('Metformin 500 mg');
const METFORMIN_850 = D('Metformin 850 mg');
const MELOXICAM = D('Meloxicam 7,5 mg');
const EPERISON = D('Eperison 50 mg');
const ORESOL = D('Oresol (muối bù nước)');
const RACECADOTRIL = D('Racecadotril 100 mg');
const LACTOBACILLUS = D('Men vi sinh Lactobacillus');

/**
 * Bộ ca nội tổng quát: 3 ca làm quen (NL1–NL3) và 12 ca tính số đo (N01–N12).
 * MINH HỌA, chưa được cố vấn y khoa duyệt. Tên, ngày sinh đều là giả.
 * Ngày sinh rơi vào tháng 4–9 để tuổi không đổi trong suốt khoảng thử (10/2026 – 03/2027).
 */
export const NOI_CASES: readonly TrialCase[] = [
  {
    id: 'NL1',
    specialty: 'noi',
    warmup: true,
    title: 'Cảm, sổ mũi (làm quen: đơn mẫu)',
    scenarios: ['don-mau'],
    patient: { fullName: 'Phạm Văn Tùng', gender: 'male', birthDate: '1988-04-12', ageLabel: '38 tuổi', hasCccd: true },
    reason: 'Sổ mũi, ho 2 ngày',
    story: ['Sổ mũi, hắt hơi, ho khan từ 2 ngày nay.', 'Người hơi mệt, không sốt.'],
    ifAsked: ['Không khó thở, không đau ngực.', 'Không dị ứng thuốc.', 'Chưa uống thuốc gì.'],
    vitals: { temperatureC: 37.2, pulse: 78, systolic: 120, diastolic: 78, weightKg: 66 },
    findings: 'Họng hơi đỏ, phổi thông khí đều, không ran.',
    allergies: [],
    history: [],
    steps: [{ do: 'template', id: 'nhiem-tru-ho-hap-tren' }],
    final: { dx: ['J06.9'], lines: [{ drug: PARACETAMOL, quantity: 10 }, { drug: CETIRIZIN, days: 5 }, { drug: NACL, quantity: 1 }], acks: [] },
    note: 'Làm quen với màn hình khám: nhập sinh hiệu, chọn đơn mẫu, "Ký & In".',
  },
  {
    id: 'NL2',
    specialty: 'noi',
    warmup: true,
    title: 'Viêm họng, dị ứng penicillin (làm quen: cảnh báo)',
    scenarios: ['di-ung'],
    patient: { fullName: 'Lê Thị Hồng Nhung', gender: 'female', birthDate: '1979-09-03', ageLabel: '47 tuổi', hasCccd: true },
    reason: 'Đau họng, sốt nhẹ',
    story: ['Đau họng, nuốt đau từ hôm qua.', 'Sốt nhẹ về chiều.'],
    ifAsked: ['Từng nổi mẩn ngứa khắp người khi uống amoxicillin (đã ghi trong hồ sơ).', 'Không ho, không khó thở.'],
    vitals: { temperatureC: 38.1, pulse: 88, systolic: 118, diastolic: 76, weightKg: 54 },
    findings: 'Họng đỏ, amidan sưng nhẹ, không mủ. Hạch góc hàm không to.',
    allergies: [{ kind: 'class', value: 'penicillin' }],
    history: [],
    steps: [
      { do: 'template', id: 'viem-hong-cap' },
      { do: 'expect', rule: 'allergy' },
      { do: 'remove', drug: AMOXICILLIN },
      { do: 'add', query: 'azithromycin', drug: AZITHROMYCIN },
    ],
    final: { dx: ['J02.9'], lines: [{ drug: PARACETAMOL, quantity: 10 }, { drug: AZITHROMYCIN, days: 3 }], acks: [] },
    note: 'Làm quen với cảnh báo: đơn mẫu có amoxicillin nên máy cảnh báo dị ứng. Cho bác sĩ thấy hai lối ra: bỏ thuốc và thêm thuốc khác, hoặc ghi lý do vẫn kê.',
  },
  {
    id: 'NL3',
    specialty: 'noi',
    warmup: true,
    title: 'Tái khám tăng huyết áp (làm quen: kê lại)',
    scenarios: ['ke-lai'],
    patient: { fullName: 'Trần Văn Bảy', gender: 'male', birthDate: '1958-06-20', ageLabel: '68 tuổi', hasCccd: true },
    reason: 'Tái khám tăng huyết áp, hết thuốc',
    story: ['Đến xin kê lại thuốc huyết áp như lần trước, đã hết thuốc.', 'Uống đều mỗi sáng, người khỏe.'],
    ifAsked: ['Không đau đầu, không chóng mặt, không phù chân.', 'Không dị ứng thuốc.'],
    vitals: { pulse: 74, systolic: 134, diastolic: 82, weightKg: 61 },
    findings: 'Tim đều, phổi trong, không phù.',
    allergies: [],
    history: ['Tăng huyết áp 10 năm, đang dùng amlodipin'],
    prior: {
      daysAgo: 100,
      reason: 'Tái khám tăng huyết áp',
      symptoms: 'Không đau đầu, không chóng mặt',
      findings: 'Tim đều, không phù',
      vitals: { pulse: 76, systolic: 138, diastolic: 86, weightKg: 62 },
      dx: ['I10'],
      lines: [{ drug: AMLODIPIN, perDose: 1, timesPerDay: 1, days: 30 }],
      advice: 'Uống thuốc đều mỗi sáng, hạn chế muối. Đo huyết áp tại nhà.',
    },
    steps: [{ do: 'repeat' }],
    final: { dx: ['I10'], lines: [{ drug: AMLODIPIN, days: 30, quantity: 30 }], acks: [] },
    note: 'Làm quen với nút "Kê lại đơn này" ở cột lịch sử khám bên trái.',
  },
  {
    id: 'N01',
    specialty: 'noi',
    warmup: false,
    title: 'Viêm họng cấp',
    scenarios: ['don-mau'],
    patient: { fullName: 'Nguyễn Thị Mai Hoa', gender: 'female', birthDate: '1992-06-18', ageLabel: '34 tuổi', hasCccd: true },
    reason: 'Đau họng, sốt 2 ngày',
    story: ['Đau rát họng, nuốt đau từ 2 ngày nay.', 'Sốt, tối qua đo ở nhà 38,5 độ.'],
    ifAsked: ['Không ho, không sổ mũi.', 'Không dị ứng thuốc.', 'Không có thai, không cho con bú.'],
    vitals: { temperatureC: 38.4, pulse: 92, systolic: 112, diastolic: 72, weightKg: 52 },
    findings: 'Họng đỏ rực, amidan sưng, có chấm mủ trắng. Hạch góc hàm sưng đau.',
    allergies: [],
    history: [],
    steps: [{ do: 'template', id: 'viem-hong-cap' }],
    final: { dx: ['J02.9'], lines: [{ drug: AMOXICILLIN, days: 5, quantity: 15 }, { drug: PARACETAMOL, quantity: 10 }], acks: [] },
    note: 'Ca thường: đơn mẫu "Viêm họng cấp có chỉ định kháng sinh", không có cảnh báo.',
  },
  {
    id: 'N02',
    specialty: 'noi',
    warmup: false,
    title: 'Viêm dạ dày',
    scenarios: ['don-mau'],
    patient: { fullName: 'Hoàng Văn Thắng', gender: 'male', birthDate: '1981-08-05', ageLabel: '45 tuổi', hasCccd: true },
    reason: 'Đau thượng vị, đầy bụng',
    story: ['Đau âm ỉ vùng trên rốn khoảng 1 tuần, đau hơn khi đói.', 'Ợ hơi, đầy bụng sau ăn.'],
    ifAsked: ['Không nôn, không đi ngoài phân đen.', 'Hay uống cà phê, thỉnh thoảng uống rượu bia.', 'Không dị ứng thuốc.'],
    vitals: { temperatureC: 36.8, pulse: 76, systolic: 124, diastolic: 80, weightKg: 68 },
    findings: 'Ấn thượng vị đau nhẹ, bụng mềm, không có phản ứng thành bụng.',
    allergies: [],
    history: [],
    steps: [{ do: 'template', id: 'viem-da-day' }],
    final: { dx: ['K29.7'], lines: [{ drug: OMEPRAZOL, days: 14 }, { drug: DOMPERIDON, days: 7 }, { drug: ANTACID, days: 7 }], acks: [] },
    note: 'Ca thường: đơn mẫu "Viêm dạ dày" (3 thuốc), không có cảnh báo.',
  },
  {
    id: 'N03',
    specialty: 'noi',
    warmup: false,
    title: 'Viêm họng cấp, bệnh nhân dị ứng penicillin',
    scenarios: ['di-ung', 'don-mau'],
    patient: { fullName: 'Đỗ Thị Thu Thảo', gender: 'female', birthDate: '1995-04-27', ageLabel: '31 tuổi', hasCccd: true },
    reason: 'Đau họng, sốt',
    story: ['Đau họng 3 ngày, nuốt vướng.', 'Sốt về chiều, người mỏi.'],
    ifAsked: ['Năm ngoái uống amoxicillin thì nổi mề đay toàn thân, phải đi tiêm (đã ghi trong hồ sơ).', 'Không khó thở.'],
    vitals: { temperatureC: 38.6, pulse: 96, systolic: 110, diastolic: 70, weightKg: 49 },
    findings: 'Họng đỏ, amidan sưng to, có mủ. Hạch góc hàm hai bên sưng đau.',
    allergies: [{ kind: 'class', value: 'penicillin' }],
    history: [],
    steps: [
      { do: 'template', id: 'viem-hong-cap' },
      { do: 'expect', rule: 'allergy' },
      { do: 'remove', drug: AMOXICILLIN },
      { do: 'add', query: 'azithromycin', drug: AZITHROMYCIN },
    ],
    final: { dx: ['J02.9'], lines: [{ drug: PARACETAMOL, quantity: 10 }, { drug: AZITHROMYCIN, days: 3, quantity: 3 }], acks: [] },
    note: 'Đơn mẫu viêm họng có amoxicillin: máy phải cảnh báo dị ứng penicillin và khóa nút ký. Ghi lại bác sĩ đổi thuốc hay ghi lý do vẫn kê.',
  },
  {
    id: 'N04',
    specialty: 'noi',
    warmup: false,
    title: 'Tăng huyết áp, xin đơn 90 ngày',
    scenarios: ['man-tinh-90', 'don-mau'],
    patient: { fullName: 'Vũ Đình Khôi', gender: 'male', birthDate: '1962-07-14', ageLabel: '64 tuổi', hasCccd: true },
    reason: 'Tái khám tăng huyết áp',
    story: ['Tái khám huyết áp, đang uống amlodipin 5 mg mỗi sáng, huyết áp ở nhà ổn.', 'Sắp về quê ở với con 3 tháng, xin bác sĩ kê đủ thuốc 90 ngày.'],
    ifAsked: ['Không đau đầu, không phù chân, không hồi hộp.', 'Không dị ứng thuốc.'],
    vitals: { pulse: 72, systolic: 132, diastolic: 80, weightKg: 64 },
    findings: 'Tim đều, không phù, phổi trong.',
    allergies: [],
    history: ['Tăng huyết áp 5 năm, đang dùng amlodipin 5 mg'],
    steps: [
      { do: 'template', id: 'tang-huyet-ap-tai-kham' },
      { do: 'set', drug: AMLODIPIN, days: '90' },
    ],
    final: { dx: ['I10', 'Z76.0'], lines: [{ drug: AMLODIPIN, days: 90, quantity: 90 }], acks: [] },
    note: 'Bệnh mạn tính được kê tối đa 90 ngày (bệnh khác tối đa 30). Sửa "Số ngày" thành 90: máy không chặn vì chẩn đoán I10 là mạn tính.',
  },
  {
    id: 'N05',
    specialty: 'noi',
    warmup: false,
    title: 'Tăng huyết áp và rối loạn lipid máu, kê lại đơn cũ',
    scenarios: ['ke-lai'],
    patient: { fullName: 'Bùi Thị Kim Liên', gender: 'female', birthDate: '1960-05-30', ageLabel: '66 tuổi', hasCccd: true },
    reason: 'Tái khám, xin kê lại thuốc',
    story: ['Đến tái khám huyết áp và mỡ máu, xin kê lại đúng thuốc lần trước.', 'Uống thuốc đều, không thấy khó chịu gì.'],
    ifAsked: ['Không đau cơ, không mệt.', 'Không dị ứng thuốc.'],
    vitals: { pulse: 70, systolic: 128, diastolic: 78, weightKg: 57 },
    findings: 'Tim đều, không phù.',
    allergies: [],
    history: ['Tăng huyết áp, rối loạn lipid máu'],
    prior: {
      daysAgo: 98,
      reason: 'Tái khám tăng huyết áp, mỡ máu',
      symptoms: 'Không đau đầu, không đau cơ',
      findings: 'Tim đều, không phù',
      vitals: { pulse: 72, systolic: 130, diastolic: 80, weightKg: 57 },
      dx: ['I10', 'E78.5'],
      lines: [
        { drug: AMLODIPIN, perDose: 1, timesPerDay: 1, days: 30 },
        { drug: ATORVASTATIN, perDose: 1, timesPerDay: 1, days: 30 },
      ],
      advice: 'Uống thuốc đều, giảm muối, giảm mỡ động vật.',
    },
    steps: [{ do: 'repeat' }],
    final: { dx: ['I10', 'E78.5'], lines: [{ drug: AMLODIPIN, days: 30 }, { drug: ATORVASTATIN, days: 30 }], acks: [] },
    note: '"Kê lại đơn này" một nút: thuốc, chẩn đoán và lời dặn của lượt khám cũ được điền sẵn.',
  },
  {
    id: 'N06',
    specialty: 'noi',
    warmup: false,
    title: 'Viêm họng cấp, bệnh nhân xin thêm thuốc trùng hoạt chất',
    scenarios: ['trung-hoat-chat', 'don-mau'],
    patient: { fullName: 'Phan Quốc Việt', gender: 'male', birthDate: '1987-06-22', ageLabel: '39 tuổi', hasCccd: true },
    reason: 'Đau họng, sốt',
    story: ['Đau họng, sốt 2 ngày.', 'Lần trước bị y như vậy, uống "amoxicillin có thêm acid clavulanic" thì khỏi nhanh: xin bác sĩ kê thuốc đó.'],
    ifAsked: ['Không dị ứng thuốc.', 'Không đau bụng, không tiêu chảy khi uống thuốc đó lần trước.'],
    vitals: { temperatureC: 38.3, pulse: 90, systolic: 122, diastolic: 80, weightKg: 70 },
    findings: 'Họng đỏ, amidan sưng, có mủ.',
    allergies: [],
    history: [],
    steps: [
      { do: 'template', id: 'viem-hong-cap' },
      { do: 'add', query: 'amoxicillin clav', drug: AMOX_CLAV },
      { do: 'expect', rule: 'duplicate-ingredient' },
      { do: 'remove', drug: AMOXICILLIN },
    ],
    final: { dx: ['J02.9'], lines: [{ drug: PARACETAMOL, quantity: 10 }, { drug: AMOX_CLAV, days: 5, quantity: 10 }], acks: [] },
    note: 'Đơn mẫu đã có amoxicillin; thêm amoxicillin + acid clavulanic thì máy cảnh báo trùng hoạt chất amoxicillin. Ghi lại bác sĩ bỏ một trong hai hay ghi lý do.',
  },
  {
    id: 'N07',
    specialty: 'noi',
    warmup: false,
    title: 'Nhiễm trùng hô hấp trên',
    scenarios: ['don-mau'],
    patient: { fullName: 'Đặng Thị Ngọc Ánh', gender: 'female', birthDate: '2001-08-09', ageLabel: '25 tuổi', hasCccd: true },
    reason: 'Sổ mũi, ho, đau họng nhẹ',
    story: ['Sổ mũi nước trong, hắt hơi, ho khan 3 ngày.', 'Đau họng nhẹ, không sốt.'],
    ifAsked: ['Không khó thở.', 'Không dị ứng thuốc.', 'Không có thai.'],
    vitals: { temperatureC: 37.0, pulse: 80, systolic: 108, diastolic: 70, weightKg: 48 },
    findings: 'Niêm mạc mũi phù nề, họng hơi đỏ, phổi không ran.',
    allergies: [],
    history: [],
    steps: [{ do: 'template', id: 'nhiem-tru-ho-hap-tren' }],
    final: { dx: ['J06.9'], lines: [{ drug: PARACETAMOL, quantity: 10 }, { drug: CETIRIZIN, days: 5 }, { drug: NACL, quantity: 1 }], acks: [] },
    note: 'Ca thường: đơn mẫu "Nhiễm trùng hô hấp trên cấp (không kháng sinh)".',
  },
  {
    id: 'N08',
    specialty: 'noi',
    warmup: false,
    title: 'Đau thắt lưng, bệnh nhân dị ứng thuốc kháng viêm',
    scenarios: ['di-ung', 'don-mau'],
    patient: { fullName: 'Ngô Văn Sáu', gender: 'male', birthDate: '1973-05-02', ageLabel: '53 tuổi', hasCccd: true },
    reason: 'Đau lưng sau khi bê đồ nặng',
    story: ['Đau vùng thắt lưng 2 ngày nay sau khi bê chậu cây, cúi xuống đau tăng.', 'Không lan xuống chân.'],
    ifAsked: ['Trước đây uống diclofenac thì sưng môi, sưng mắt (đã ghi trong hồ sơ).', 'Không tê chân, tiểu tiện bình thường.'],
    vitals: { temperatureC: 36.7, pulse: 78, systolic: 126, diastolic: 82, weightKg: 72 },
    findings: 'Co cứng cơ cạnh cột sống thắt lưng hai bên, ấn đau. Nâng chân thẳng không đau, phản xạ gân xương bình thường.',
    allergies: [{ kind: 'class', value: 'nsaid' }],
    history: [],
    steps: [
      { do: 'template', id: 'dau-that-lung' },
      { do: 'expect', rule: 'allergy' },
      { do: 'remove', drug: MELOXICAM },
      { do: 'remove', drug: OMEPRAZOL },
      { do: 'add', query: 'paracetamol 500', drug: PARACETAMOL },
      { do: 'expect', rule: 'incomplete-line' },
      { do: 'set', drug: PARACETAMOL, quantity: '15' },
    ],
    final: { dx: ['M54.5'], lines: [{ drug: EPERISON, days: 5 }, { drug: PARACETAMOL, perDose: 1, quantity: 15 }], acks: [] },
    note: 'Đơn mẫu đau lưng có meloxicam (thuốc kháng viêm không steroid): máy phải cảnh báo dị ứng. Thuốc dùng khi cần (paracetamol) phải tự nhập số lượng.',
  },
  {
    id: 'N09',
    specialty: 'noi',
    warmup: false,
    title: 'Đái tháo đường typ 2, kê lại và xin đơn 90 ngày',
    scenarios: ['ke-lai', 'man-tinh-90'],
    patient: { fullName: 'Lý Thị Bích Vân', gender: 'female', birthDate: '1966-05-21', ageLabel: '60 tuổi', hasCccd: true },
    reason: 'Tái khám đái tháo đường',
    story: ['Tái khám tiểu đường, đường huyết đo ở nhà buổi sáng khoảng 6–7.', 'Nhà xa, đi lại khó: xin bác sĩ kê thuốc cũ đủ 3 tháng.'],
    ifAsked: ['Không khát nhiều, không sụt cân, không tê chân.', 'Không dị ứng thuốc.'],
    vitals: { pulse: 76, systolic: 124, diastolic: 78, weightKg: 58 },
    findings: 'Tim phổi bình thường, bàn chân không loét.',
    allergies: [],
    history: ['Đái tháo đường typ 2, đang dùng metformin'],
    prior: {
      daysAgo: 96,
      reason: 'Tái khám đái tháo đường',
      symptoms: 'Không khát nhiều, không sụt cân',
      findings: 'Bàn chân không loét',
      vitals: { pulse: 78, systolic: 126, diastolic: 80, weightKg: 58 },
      dx: ['E11.9'],
      lines: [{ drug: METFORMIN_500, perDose: 1, timesPerDay: 2, days: 30 }],
      advice: 'Theo dõi đường huyết. Chế độ ăn hợp lý.',
    },
    steps: [{ do: 'repeat' }, { do: 'set', drug: METFORMIN_500, days: '90' }],
    final: { dx: ['E11.9'], lines: [{ drug: METFORMIN_500, days: 90, quantity: 180 }], acks: [] },
    note: 'Kê lại rồi sửa số ngày thành 90: được phép vì E11.9 là bệnh mạn tính.',
  },
  {
    id: 'N10',
    specialty: 'noi',
    warmup: false,
    title: 'Tiêu chảy cấp',
    scenarios: ['don-mau'],
    patient: { fullName: 'Hồ Minh Trí', gender: 'male', birthDate: '1998-05-11', ageLabel: '28 tuổi', hasCccd: true },
    reason: 'Đi ngoài phân lỏng từ đêm qua',
    story: ['Đi ngoài phân lỏng 5–6 lần từ đêm qua, sau khi ăn hải sản ở quán.', 'Đau quặn bụng từng cơn, hơi mệt.'],
    ifAsked: ['Phân không có máu, không sốt, không nôn.', 'Vẫn uống được nước.', 'Không dị ứng thuốc.'],
    vitals: { temperatureC: 37.1, pulse: 86, systolic: 114, diastolic: 72, weightKg: 63 },
    findings: 'Bụng mềm, ấn đau nhẹ quanh rốn, không có dấu mất nước.',
    allergies: [],
    history: [],
    steps: [{ do: 'template', id: 'tieu-chay-cap' }],
    final: { dx: ['A09'], lines: [{ drug: ORESOL, quantity: 10 }, { drug: RACECADOTRIL, days: 3 }, { drug: LACTOBACILLUS, days: 7 }], acks: [] },
    note: 'Ca thường: đơn mẫu "Tiêu chảy cấp (người lớn, không kháng sinh)".',
  },
  {
    id: 'N11',
    specialty: 'noi',
    warmup: false,
    title: 'Viêm mũi dị ứng tái phát, kê lại đơn cũ',
    scenarios: ['ke-lai'],
    patient: { fullName: 'Dương Thị Thanh Tâm', gender: 'female', birthDate: '1984-07-07', ageLabel: '42 tuổi', hasCccd: true },
    reason: 'Hắt hơi, ngạt mũi tái phát',
    story: ['Trời trở lạnh lại hắt hơi liên tục buổi sáng, ngạt mũi, chảy nước mũi trong.', 'Lần trước bác sĩ kê thuốc uống thấy đỡ: xin kê lại.'],
    ifAsked: ['Không sốt, không đau đầu.', 'Không dị ứng thuốc.', 'Uống thuốc lần trước có hơi buồn ngủ nhưng chịu được.'],
    vitals: { temperatureC: 36.6, pulse: 74, systolic: 112, diastolic: 72, weightKg: 53 },
    findings: 'Niêm mạc mũi nhợt, phù nề, dịch trong.',
    allergies: [],
    history: ['Viêm mũi dị ứng theo mùa'],
    prior: {
      daysAgo: 120,
      reason: 'Hắt hơi, ngạt mũi',
      symptoms: 'Hắt hơi từng cơn buổi sáng, ngạt mũi',
      findings: 'Niêm mạc mũi nhợt, phù nề',
      vitals: { temperatureC: 36.6, pulse: 72, systolic: 110, diastolic: 70, weightKg: 53 },
      dx: ['J30.4'],
      lines: [
        { drug: CETIRIZIN, perDose: 1, timesPerDay: 1, days: 14 },
        { drug: NACL, quantity: 1, instruction: NACL_MUI },
      ],
      advice: 'Tránh bụi, giữ ấm.',
    },
    steps: [{ do: 'repeat' }],
    final: { dx: ['J30.4'], lines: [{ drug: CETIRIZIN, days: 14, quantity: 14 }, { drug: NACL, quantity: 1 }], acks: [] },
    note: '"Kê lại đơn này" với đơn có thuốc nhỏ mũi (cách dùng gõ tay được mang sang).',
  },
  {
    id: 'N12',
    specialty: 'noi',
    warmup: false,
    title: 'Đái tháo đường typ 2, tăng liều metformin',
    scenarios: ['ke-lai', 'trung-hoat-chat'],
    patient: { fullName: 'Trịnh Văn Lợi', gender: 'male', birthDate: '1969-04-25', ageLabel: '57 tuổi', hasCccd: true },
    reason: 'Tái khám đái tháo đường, đường huyết còn cao',
    story: ['Tái khám tiểu đường. Đang uống metformin 500 mg sáng 1 viên, tối 1 viên.', 'Đường huyết đo ở nhà buổi sáng vẫn 8–9.'],
    ifAsked: ['Uống thuốc đều, không đau bụng, không tiêu chảy.', 'Không dị ứng thuốc.', 'Ăn uống chưa kiêng được nhiều.'],
    vitals: { pulse: 80, systolic: 130, diastolic: 82, weightKg: 74 },
    findings: 'Tim phổi bình thường, bàn chân không loét.',
    allergies: [],
    history: ['Đái tháo đường typ 2, đang dùng metformin 500 mg x 2'],
    prior: {
      daysAgo: 97,
      reason: 'Tái khám đái tháo đường',
      symptoms: 'Không khát nhiều',
      findings: 'Bàn chân không loét',
      vitals: { pulse: 78, systolic: 128, diastolic: 80, weightKg: 75 },
      dx: ['E11.9'],
      lines: [{ drug: METFORMIN_500, perDose: 1, timesPerDay: 2, days: 30 }],
      advice: 'Theo dõi đường huyết. Chế độ ăn hợp lý.',
    },
    steps: [
      { do: 'repeat' },
      { do: 'add', query: 'metformin 850', drug: METFORMIN_850 },
      { do: 'expect', rule: 'duplicate-ingredient' },
      { do: 'remove', drug: METFORMIN_500 },
    ],
    final: { dx: ['E11.9'], lines: [{ drug: METFORMIN_850, days: 30, quantity: 60 }], acks: [] },
    note: 'Kê lại đơn cũ rồi đổi hàm lượng: khi cả metformin 500 mg và 850 mg cùng nằm trong đơn, máy cảnh báo trùng hoạt chất cho tới khi bỏ một thuốc (hoặc ghi lý do).',
  },
];
