import { drugCode } from '@phongmach/catalogs';
import type { TrialCase } from './types.js';

const D = drugCode;
const NACL_MUI = 'Nhỏ mỗi bên mũi 2–3 giọt, 3–4 lần/ngày';

const PARA_150 = D('Paracetamol 150 mg (gói)');
const PARA_250 = D('Paracetamol 250 mg (gói)');
const NACL = D('Natri clorid 0,9% (nhỏ mũi)');
const ORESOL = D('Oresol (muối bù nước)');
const ZINC = D('Kẽm 10 mg');
const LACTOBACILLUS = D('Men vi sinh Lactobacillus');
const AMOX_250 = D('Amoxicillin 250 mg (gói)');
const CEFIXIM_100 = D('Cefixim 100 mg (gói)');
const IBUPROFEN_SIRO = D('Ibuprofen 100 mg/5 ml (siro)');
const RACECADOTRIL_30 = D('Racecadotril 30 mg (gói)');
const MONTELUKAST = D('Montelukast 10 mg');

/**
 * Bộ ca nhi: 3 ca làm quen (PL1–PL3) và 12 ca tính số đo (P01–P12).
 * MINH HỌA, chưa được cố vấn y khoa duyệt. Tên, ngày sinh đều là giả. Thuốc dạng trẻ em trong danh mục để trống liều:
 * bác sĩ phải tự nhập theo cân nặng; liều trong `steps` chỉ là liều bài diễn tập kỹ thuật gõ vào.
 * Ngày sinh được chọn để trong suốt khoảng thử (10/2026 – 03/2027) không ca nào vượt ngưỡng tuổi của quy tắc (dưới 12, từ 14).
 */
export const NHI_CASES: readonly TrialCase[] = [
  {
    id: 'PL1',
    specialty: 'nhi',
    warmup: true,
    title: 'Sốt siêu vi (làm quen: đơn mẫu, nhập liều)',
    scenarios: ['don-mau'],
    patient: { fullName: 'Nguyễn Gia Huy', gender: 'male', birthDate: '2023-05-15', ageLabel: '3 tuổi', hasCccd: false },
    companion: 'Mẹ bé',
    reason: 'Sốt từ đêm qua',
    story: ['Bé sốt từ đêm qua, cao nhất 38,8 độ, uống hạ sốt thì giảm.', 'Vẫn chơi, ăn kém hơn mọi ngày.'],
    ifAsked: ['Không ho, không nôn, không tiêu chảy, không phát ban.', 'Không dị ứng thuốc.', 'Tiêm chủng đủ.'],
    vitals: { temperatureC: 38.6, pulse: 118, weightKg: 14 },
    findings: 'Bé tỉnh, họng hơi đỏ, phổi trong, không ban, cổ mềm.',
    allergies: [],
    history: [],
    steps: [
      { do: 'template', id: 'sot-virus-tre-em' },
      { do: 'expect', rule: 'incomplete-line' },
      { do: 'set', drug: PARA_150, perDose: '1' },
    ],
    final: { dx: ['B34.9'], lines: [{ drug: PARA_150, perDose: 1, quantity: 6 }], acks: [] },
    note: 'Làm quen: thuốc dạng trẻ em để trống liều, bác sĩ phải nhập "Liều/lần" theo cân nặng thì mới ký được.',
  },
  {
    id: 'PL2',
    specialty: 'nhi',
    warmup: true,
    title: 'Ho, sổ mũi, chưa có cân nặng (làm quen: cảnh báo cân nặng)',
    scenarios: ['thieu-can-nang', 'don-mau'],
    patient: { fullName: 'Trần Ngọc Bảo Anh', gender: 'female', birthDate: '2022-06-10', ageLabel: '4 tuổi', hasCccd: false },
    companion: 'Bố bé',
    reason: 'Ho, sổ mũi 3 ngày',
    story: ['Bé ho, sổ mũi 3 ngày, đêm ngạt mũi khó ngủ.', 'Hôm qua sốt nhẹ 38 độ.'],
    ifAsked: ['Chưa cân cho bé ở phòng khám. Tuần trước cân ở trường mầm non là 16 kg.', 'Không khó thở, bú và ăn được.', 'Không dị ứng thuốc.'],
    vitals: { temperatureC: 37.8, pulse: 110 },
    findings: 'Mũi chảy dịch trong, họng đỏ nhẹ, phổi không ran, không co kéo.',
    allergies: [],
    history: [],
    steps: [
      { do: 'template', id: 'ho-cam-tre-em' },
      { do: 'expect', rule: 'no-weight' },
      { do: 'weight', kg: '16' },
      { do: 'set', drug: PARA_150, perDose: '1' },
    ],
    final: { dx: ['J06.9'], lines: [{ drug: NACL, quantity: 2 }, { drug: PARA_150, perDose: 1, quantity: 6 }], acks: [] },
    note: 'Làm quen: phiếu điều dưỡng không có cân nặng nên máy cảnh báo. Bác sĩ hỏi người nhà rồi nhập cân nặng, hoặc ghi lý do.',
  },
  {
    id: 'PL3',
    specialty: 'nhi',
    warmup: true,
    title: 'Ho, sổ mũi tái lại (làm quen: kê lại)',
    scenarios: ['ke-lai'],
    patient: { fullName: 'Lê Minh Quân', gender: 'male', birthDate: '2021-04-08', ageLabel: '5 tuổi', hasCccd: false },
    companion: 'Mẹ bé',
    reason: 'Ho, sổ mũi, sốt nhẹ',
    story: ['Bé lại ho, sổ mũi, sốt nhẹ giống đợt trước.', 'Đợt trước bác sĩ kê thuốc uống 3 ngày là khỏi: xin kê lại.'],
    ifAsked: ['Không khó thở, không nôn.', 'Không dị ứng thuốc.'],
    vitals: { temperatureC: 38.0, pulse: 104, weightKg: 18 },
    findings: 'Họng đỏ nhẹ, mũi chảy dịch trong, phổi không ran.',
    allergies: [],
    history: [],
    prior: {
      daysAgo: 110,
      reason: 'Ho, sổ mũi',
      symptoms: 'Ho, sổ mũi, sốt nhẹ',
      findings: 'Họng đỏ, phổi không ran',
      vitals: { temperatureC: 38.1, pulse: 106, weightKg: 17.5 },
      dx: ['J06.9'],
      lines: [
        { drug: NACL, quantity: 2, instruction: NACL_MUI },
        { drug: PARA_250, perDose: 1, quantity: 6 },
      ],
      advice: 'Vệ sinh mũi bằng nước muối sinh lý. Tái khám nếu khó thở, thở nhanh hoặc sốt trên 3 ngày.',
    },
    steps: [{ do: 'repeat' }],
    final: { dx: ['J06.9'], lines: [{ drug: NACL, quantity: 2 }, { drug: PARA_250, perDose: 1, quantity: 6 }], acks: [] },
    note: 'Làm quen với nút "Kê lại đơn này": liều đã nhập ở lượt khám cũ được mang sang.',
  },
  {
    id: 'P01',
    specialty: 'nhi',
    warmup: false,
    title: 'Sốt siêu vi',
    scenarios: ['don-mau'],
    patient: { fullName: 'Phạm Bảo Châu', gender: 'female', birthDate: '2023-07-22', ageLabel: '3 tuổi', hasCccd: false },
    companion: 'Mẹ bé',
    reason: 'Sốt 2 ngày',
    story: ['Bé sốt 2 ngày nay, lúc cao nhất 39 độ.', 'Hạ sốt xong thì chơi bình thường, ăn ít hơn.'],
    ifAsked: ['Không ho, không sổ mũi, không tiêu chảy, không ban.', 'Không co giật.', 'Không dị ứng thuốc.'],
    vitals: { temperatureC: 38.7, pulse: 122, weightKg: 14 },
    findings: 'Bé tỉnh, họng đỏ nhẹ, phổi trong, không ban, cổ mềm.',
    allergies: [],
    history: [],
    steps: [
      { do: 'template', id: 'sot-virus-tre-em' },
      { do: 'set', drug: PARA_150, perDose: '1' },
    ],
    final: { dx: ['B34.9'], lines: [{ drug: PARA_150, perDose: 1, quantity: 6 }], acks: [] },
    note: 'Ca thường: đơn mẫu "Sốt, nhiễm virus ở trẻ em", nhập liều theo cân nặng.',
  },
  {
    id: 'P02',
    specialty: 'nhi',
    warmup: false,
    title: 'Ho, sổ mũi',
    scenarios: ['don-mau'],
    patient: { fullName: 'Hoàng Gia Bảo', gender: 'male', birthDate: '2024-08-30', ageLabel: '2 tuổi', hasCccd: false },
    companion: 'Bà nội',
    reason: 'Ho, sổ mũi 2 ngày',
    story: ['Cháu ho, chảy nước mũi 2 ngày, đêm ngạt mũi quấy khóc.', 'Chiều qua sốt 38 độ.'],
    ifAsked: ['Không thở khò khè, vẫn ăn cháo và bú được.', 'Không dị ứng thuốc.'],
    vitals: { temperatureC: 38.0, pulse: 124, weightKg: 12 },
    findings: 'Mũi chảy dịch trong, họng hơi đỏ, phổi không ran, không co kéo lồng ngực.',
    allergies: [],
    history: [],
    steps: [
      { do: 'template', id: 'ho-cam-tre-em' },
      { do: 'set', drug: PARA_150, perDose: '1' },
    ],
    final: { dx: ['J06.9'], lines: [{ drug: NACL, quantity: 2 }, { drug: PARA_150, perDose: 1, quantity: 6 }], acks: [] },
    note: 'Ca thường: đơn mẫu "Ho, sổ mũi ở trẻ em", nhập liều theo cân nặng.',
  },
  {
    id: 'P03',
    specialty: 'nhi',
    warmup: false,
    title: 'Tiêu chảy cấp',
    scenarios: ['don-mau'],
    patient: { fullName: 'Vũ Ngọc Diệp', gender: 'female', birthDate: '2025-02-14', ageLabel: '20 tháng', hasCccd: false },
    companion: 'Mẹ bé',
    reason: 'Đi ngoài phân lỏng từ hôm qua',
    story: ['Bé đi ngoài phân lỏng, nhiều nước 6 lần từ hôm qua.', 'Nôn 1 lần sáng nay.'],
    ifAsked: ['Phân không có máu, không nhầy.', 'Vẫn bú mẹ và uống được nước, tiểu bình thường.', 'Không dị ứng thuốc.'],
    vitals: { temperatureC: 37.4, pulse: 126, weightKg: 11 },
    findings: 'Bé tỉnh, mắt không trũng, môi không khô, nếp véo da mất nhanh. Bụng mềm.',
    allergies: [],
    history: [],
    steps: [
      { do: 'template', id: 'tieu-chay-cap-tre-em' },
      { do: 'expect', rule: 'incomplete-line' },
      { do: 'set', drug: ZINC, perDose: '2' },
    ],
    final: { dx: ['A09'], lines: [{ drug: ORESOL, quantity: 10 }, { drug: ZINC, perDose: 2, days: 10, quantity: 20 }, { drug: LACTOBACILLUS, days: 7 }], acks: [] },
    note: 'Ca thường: đơn mẫu "Tiêu chảy cấp ở trẻ em" (3 thuốc), nhập liều kẽm.',
  },
  {
    id: 'P04',
    specialty: 'nhi',
    warmup: false,
    title: 'Viêm amidan cấp, trẻ dị ứng penicillin',
    scenarios: ['di-ung', 'khong-don-mau'],
    patient: { fullName: 'Đặng Minh Khôi', gender: 'male', birthDate: '2019-06-03', ageLabel: '7 tuổi', hasCccd: false },
    companion: 'Mẹ bé',
    reason: 'Sốt, đau họng',
    story: ['Bé sốt cao 39 độ 2 ngày, kêu đau họng, nuốt đau, bỏ ăn.', 'Hơi thở hôi.'],
    ifAsked: ['Năm 4 tuổi uống amoxicillin thì nổi ban đỏ khắp người (đã ghi trong hồ sơ).', 'Không ho, không khó thở.'],
    vitals: { temperatureC: 39.0, pulse: 112, weightKg: 24 },
    findings: 'Amidan hai bên sưng to, đỏ, có mủ trắng. Hạch góc hàm sưng đau. Phổi trong.',
    allergies: [{ kind: 'class', value: 'penicillin' }],
    history: [],
    steps: [
      { do: 'dx', query: 'J03', code: 'J03.9' },
      { do: 'add', query: 'amoxicillin 250', drug: AMOX_250 },
      { do: 'expect', rule: 'allergy' },
      { do: 'remove', drug: AMOX_250 },
      { do: 'add', query: 'cefixim 100', drug: CEFIXIM_100 },
      { do: 'set', drug: CEFIXIM_100, perDose: '1' },
      { do: 'add', query: 'paracetamol 250', drug: PARA_250 },
      { do: 'set', drug: PARA_250, perDose: '1', quantity: '6' },
    ],
    final: { dx: ['J03.9'], lines: [{ drug: CEFIXIM_100, perDose: 1, timesPerDay: 2, days: 5, quantity: 10 }, { drug: PARA_250, perDose: 1, quantity: 6 }], acks: [] },
    note: 'Không có đơn mẫu: bác sĩ gõ chẩn đoán và từng thuốc. Nếu chọn amoxicillin, máy phải cảnh báo dị ứng penicillin. Ghi lại bác sĩ chọn thuốc nào; cố vấn y khoa cần cho ý kiến về lựa chọn thay thế trong bài diễn tập (cefixim).',
  },
  {
    id: 'P05',
    specialty: 'nhi',
    warmup: false,
    title: 'Sốt, phiếu chưa có cân nặng (hỏi được)',
    scenarios: ['thieu-can-nang', 'don-mau'],
    patient: { fullName: 'Bùi Thảo Nguyên', gender: 'female', birthDate: '2022-05-19', ageLabel: '4 tuổi', hasCccd: false },
    companion: 'Mẹ bé',
    reason: 'Sốt từ sáng',
    story: ['Bé sốt từ sáng nay 38,5 độ, hơi mệt, vẫn uống sữa được.', 'Ở lớp đang có mấy bạn sốt.'],
    ifAsked: ['Hôm nay chưa cân. Tuần trước cân ở trường là 16 kg.', 'Không ho, không nôn, không ban.', 'Không dị ứng thuốc.'],
    vitals: { temperatureC: 38.5, pulse: 116 },
    findings: 'Bé tỉnh, họng đỏ nhẹ, phổi trong, không ban.',
    allergies: [],
    history: [],
    steps: [
      { do: 'template', id: 'sot-virus-tre-em' },
      { do: 'expect', rule: 'no-weight' },
      { do: 'weight', kg: '16' },
      { do: 'set', drug: PARA_150, perDose: '1' },
    ],
    final: { dx: ['B34.9'], lines: [{ drug: PARA_150, perDose: 1, quantity: 6 }], acks: [] },
    note: 'Phiếu điều dưỡng không có cân nặng: máy cảnh báo "trẻ chưa được ghi cân nặng". Người nhà chỉ nói cân nặng khi bác sĩ hỏi. Ghi lại bác sĩ nhập cân nặng hay ghi lý do.',
  },
  {
    id: 'P06',
    specialty: 'nhi',
    warmup: false,
    title: 'Sổ mũi ở trẻ nhũ nhi, không cân được',
    scenarios: ['thieu-can-nang', 'don-mau'],
    patient: { fullName: 'Ngô Đức Anh', gender: 'male', birthDate: '2026-01-20', ageLabel: '9 tháng', hasCccd: false },
    companion: 'Mẹ bé',
    reason: 'Sổ mũi, ngạt mũi',
    story: ['Bé sổ mũi, ngạt mũi 2 ngày, bú hay phải nhả ra để thở.', 'Không sốt.'],
    ifAsked: ['Cân của phòng khám đang hỏng nên chưa cân. Mẹ không nhớ cân nặng lần cân gần nhất.', 'Không ho nhiều, không khò khè.', 'Không dị ứng thuốc.'],
    vitals: { temperatureC: 37.0, pulse: 130 },
    findings: 'Mũi nhiều dịch trong, họng không đỏ, phổi không ran, không co kéo.',
    allergies: [],
    history: [],
    steps: [
      { do: 'template', id: 'ho-cam-tre-em' },
      { do: 'remove', drug: PARA_150 },
      { do: 'expect', rule: 'no-weight' },
      { do: 'ack', rule: 'no-weight', reason: 'Chỉ kê nước muối nhỏ mũi, không có thuốc tính theo cân nặng' },
    ],
    final: { dx: ['J06.9'], lines: [{ drug: NACL, quantity: 2 }], acks: ['no-weight'] },
    note: 'Không lấy được cân nặng: bác sĩ phải ghi lý do thì mới ký được. Trong bài diễn tập, đơn chỉ còn nước muối nhỏ mũi nên lý do là "không có thuốc tính theo cân nặng".',
  },
  {
    id: 'P07',
    specialty: 'nhi',
    warmup: false,
    title: 'Sốt siêu vi, đổi hàm lượng thuốc hạ sốt',
    scenarios: ['trung-hoat-chat', 'don-mau'],
    patient: { fullName: 'Lý Hải Đăng', gender: 'male', birthDate: '2020-09-12', ageLabel: '6 tuổi', hasCccd: false },
    companion: 'Bố bé',
    reason: 'Sốt 1 ngày',
    story: ['Bé sốt từ chiều qua, 38,8 độ, kêu đau đầu, mỏi người.', 'Ở nhà còn gói hạ sốt 150 mg của em bé, uống 1 gói không thấy hạ.'],
    ifAsked: ['Không ho, không nôn, không ban.', 'Không dị ứng thuốc.'],
    vitals: { temperatureC: 38.8, pulse: 108, weightKg: 20 },
    findings: 'Bé tỉnh, họng đỏ nhẹ, phổi trong, cổ mềm, không ban.',
    allergies: [],
    history: [],
    steps: [
      { do: 'template', id: 'sot-virus-tre-em' },
      { do: 'add', query: 'paracetamol 250', drug: PARA_250 },
      { do: 'expect', rule: 'duplicate-ingredient' },
      { do: 'remove', drug: PARA_150 },
      { do: 'set', drug: PARA_250, perDose: '1', quantity: '6' },
    ],
    final: { dx: ['B34.9'], lines: [{ drug: PARA_250, perDose: 1, quantity: 6 }], acks: [] },
    note: 'Đơn mẫu có gói 150 mg; bé 20 kg nên bác sĩ có thể đổi sang gói 250 mg. Khi cả hai cùng nằm trong đơn, máy cảnh báo trùng hoạt chất paracetamol.',
  },
  {
    id: 'P08',
    specialty: 'nhi',
    warmup: false,
    title: 'Ho, sổ mũi tái lại, kê lại đơn cũ',
    scenarios: ['ke-lai'],
    patient: { fullName: 'Đỗ Khánh Linh', gender: 'female', birthDate: '2022-04-02', ageLabel: '4 tuổi', hasCccd: false },
    companion: 'Mẹ bé',
    reason: 'Ho, sổ mũi, sốt nhẹ',
    story: ['Bé ho, sổ mũi lại 2 ngày nay, tối qua sốt 38 độ.', 'Đợt trước bác sĩ kê nước muối và hạ sốt, 3 ngày thì khỏi: xin kê lại như cũ.'],
    ifAsked: ['Không khó thở, ăn được.', 'Không dị ứng thuốc.'],
    vitals: { temperatureC: 37.9, pulse: 108, weightKg: 16 },
    findings: 'Mũi chảy dịch trong, họng đỏ nhẹ, phổi không ran.',
    allergies: [],
    history: [],
    prior: {
      daysAgo: 105,
      reason: 'Ho, sổ mũi',
      symptoms: 'Ho, sổ mũi, sốt nhẹ',
      findings: 'Họng đỏ nhẹ, phổi không ran',
      vitals: { temperatureC: 38.0, pulse: 110, weightKg: 15.5 },
      dx: ['J06.9'],
      lines: [
        { drug: NACL, quantity: 2, instruction: NACL_MUI },
        { drug: PARA_150, perDose: 1, quantity: 6 },
      ],
      advice: 'Vệ sinh mũi bằng nước muối sinh lý. Tái khám nếu khó thở, thở nhanh hoặc sốt trên 3 ngày.',
    },
    steps: [{ do: 'repeat' }],
    final: { dx: ['J06.9'], lines: [{ drug: NACL, quantity: 2 }, { drug: PARA_150, perDose: 1, quantity: 6 }], acks: [] },
    note: '"Kê lại đơn này" một nút: liều đã nhập ở lượt khám cũ được mang sang.',
  },
  {
    id: 'P09',
    specialty: 'nhi',
    warmup: false,
    title: 'Hen ở thiếu niên, kê lại và xin đơn 90 ngày',
    scenarios: ['ke-lai', 'man-tinh-90'],
    patient: { fullName: 'Trịnh Quốc Bảo', gender: 'male', birthDate: '2011-05-25', ageLabel: '15 tuổi', hasCccd: true },
    companion: 'Bố cháu (cháu tự kể được)',
    reason: 'Tái khám hen, hết thuốc',
    story: ['Cháu bị hen từ nhỏ, đang uống thuốc dự phòng mỗi tối, 3 tháng nay không lên cơn.', 'Cháu sắp vào kỳ thi và ở nội trú: xin bác sĩ kê thuốc cũ đủ 3 tháng.'],
    ifAsked: ['Không ho đêm, không khò khè, chơi thể thao được.', 'Không dị ứng thuốc.'],
    vitals: { pulse: 82, respiratoryRate: 18, spo2: 98, weightKg: 52 },
    findings: 'Phổi thông khí đều hai bên, không ran rít, không ran ngáy.',
    allergies: [],
    history: ['Hen phế quản từ nhỏ'],
    prior: {
      daysAgo: 95,
      reason: 'Tái khám hen',
      symptoms: 'Không ho đêm, không khò khè',
      findings: 'Phổi không ran',
      vitals: { pulse: 80, respiratoryRate: 18, spo2: 98, weightKg: 51 },
      dx: ['J45.9'],
      lines: [{ drug: MONTELUKAST, perDose: 1, timesPerDay: 1, days: 30 }],
      advice: 'Uống thuốc đều mỗi tối. Tái khám ngay nếu khó thở, khò khè.',
    },
    steps: [{ do: 'repeat' }, { do: 'set', drug: MONTELUKAST, days: '90' }],
    final: { dx: ['J45.9'], lines: [{ drug: MONTELUKAST, days: 90, quantity: 90 }], acks: [] },
    note: 'Kê lại rồi sửa số ngày thành 90: được phép vì J45.9 (hen) là bệnh mạn tính. Bệnh nhân 15 tuổi nên đã có CCCD.',
  },
  {
    id: 'P10',
    specialty: 'nhi',
    warmup: false,
    title: 'Sốt, trẻ dị ứng ibuprofen, người nhà xin ibuprofen',
    scenarios: ['di-ung', 'don-mau'],
    patient: { fullName: 'Phan Nhã Uyên', gender: 'female', birthDate: '2023-06-27', ageLabel: '3 tuổi', hasCccd: false },
    companion: 'Bà ngoại',
    reason: 'Sốt cao từ đêm',
    story: ['Cháu sốt từ đêm, 39 độ, quấy khóc.', 'Hàng xóm bảo siro ibuprofen hạ sốt nhanh hơn: xin bác sĩ kê cho cháu siro ibuprofen.'],
    ifAsked: ['Mẹ cháu dặn là cháu từng nổi mề đay sau khi uống ibuprofen (đã ghi trong hồ sơ), bà không nhớ rõ.', 'Không ho, không nôn, không ban.'],
    vitals: { temperatureC: 39.0, pulse: 128, weightKg: 15 },
    findings: 'Bé tỉnh, họng đỏ nhẹ, phổi trong, cổ mềm, không ban.',
    allergies: [{ kind: 'ingredient', value: 'ibuprofen', label: 'Ibuprofen' }],
    history: [],
    steps: [
      { do: 'template', id: 'sot-virus-tre-em' },
      { do: 'set', drug: PARA_150, perDose: '1' },
      { do: 'add', query: 'ibuprofen siro', drug: IBUPROFEN_SIRO },
      { do: 'expect', rule: 'allergy' },
      { do: 'remove', drug: IBUPROFEN_SIRO },
    ],
    final: { dx: ['B34.9'], lines: [{ drug: PARA_150, perDose: 1, quantity: 6 }], acks: [] },
    note: 'Người nhà xin đúng thuốc trẻ dị ứng. Nếu bác sĩ thêm ibuprofen, máy phải cảnh báo dị ứng (dị ứng ghi theo hoạt chất). Bác sĩ đọc cột dị ứng và từ chối ngay cũng là kết quả đúng: ghi lại.',
  },
  {
    id: 'P11',
    specialty: 'nhi',
    warmup: false,
    title: 'Tiêu chảy cấp ở trẻ lớn, thêm thuốc vào đơn mẫu',
    scenarios: ['don-mau'],
    patient: { fullName: 'Hồ Tuấn Kiệt', gender: 'male', birthDate: '2018-08-16', ageLabel: '8 tuổi', hasCccd: false },
    companion: 'Mẹ bé',
    reason: 'Đi ngoài phân lỏng, đau bụng',
    story: ['Cháu đi ngoài phân lỏng 7–8 lần từ hôm qua sau khi ăn liên hoan ở lớp.', 'Đau bụng quanh rốn từng cơn.'],
    ifAsked: ['Phân không máu, sốt nhẹ 37,8 độ, không nôn.', 'Uống được nước.', 'Không dị ứng thuốc.'],
    vitals: { temperatureC: 37.8, pulse: 98, weightKg: 26 },
    findings: 'Bụng mềm, ấn đau nhẹ quanh rốn, không có dấu mất nước.',
    allergies: [],
    history: [],
    steps: [
      { do: 'template', id: 'tieu-chay-cap-tre-em' },
      { do: 'set', drug: ZINC, perDose: '2' },
      { do: 'add', query: 'racecadotril 30', drug: RACECADOTRIL_30 },
      { do: 'set', drug: RACECADOTRIL_30, perDose: '1', days: '3' },
    ],
    final: {
      dx: ['A09'],
      lines: [{ drug: ORESOL, quantity: 10 }, { drug: ZINC, perDose: 2, quantity: 20 }, { drug: LACTOBACILLUS, days: 7 }, { drug: RACECADOTRIL_30, perDose: 1, timesPerDay: 3, days: 3, quantity: 9 }],
      acks: [],
    },
    note: 'Đơn mẫu rồi thêm một thuốc bằng ô "Thêm thuốc" và sửa số ngày.',
  },
  {
    id: 'P12',
    specialty: 'nhi',
    warmup: false,
    title: 'Viêm tai giữa cấp, không có đơn mẫu',
    scenarios: ['khong-don-mau'],
    patient: { fullName: 'Dương Minh Anh', gender: 'female', birthDate: '2022-09-05', ageLabel: '4 tuổi', hasCccd: false },
    companion: 'Mẹ bé',
    reason: 'Đau tai, sốt',
    story: ['Bé kêu đau tai phải từ đêm qua, khóc nhiều, sốt 38,5 độ.', 'Mấy hôm trước bị sổ mũi.'],
    ifAsked: ['Tai không chảy mủ.', 'Không dị ứng thuốc.', 'Chưa uống kháng sinh đợt này.'],
    vitals: { temperatureC: 38.5, pulse: 114, weightKg: 16 },
    findings: 'Màng nhĩ phải đỏ, phồng, chưa thủng. Tai trái bình thường. Họng đỏ nhẹ.',
    allergies: [],
    history: [],
    steps: [
      { do: 'dx', query: 'H66', code: 'H66.9' },
      { do: 'add', query: 'amoxicillin 250', drug: AMOX_250 },
      { do: 'set', drug: AMOX_250, perDose: '1' },
      { do: 'add', query: 'paracetamol 150', drug: PARA_150 },
      { do: 'set', drug: PARA_150, perDose: '1', quantity: '6' },
    ],
    final: { dx: ['H66.9'], lines: [{ drug: AMOX_250, perDose: 1, timesPerDay: 3, days: 5, quantity: 15 }, { drug: PARA_150, perDose: 1, quantity: 6 }], acks: [] },
    note: 'Không có đơn mẫu: bác sĩ gõ tắt chẩn đoán và từng thuốc, nhập liều theo cân nặng. Đo phần chậm nhất của màn hình kê đơn.',
  },
];
